# 服务器 配置
server:
  # 服务器端口（http）
  port: 80
  servlet:
    context-path: /test1
#
# Spring Boot 配置
spring:
  #
  # Redis 配置
  redis:
    # 数据库名称，默认为 db0
    # 连接工厂使用的数据库索引。
    database: 0
    # Redis服务器主机。
    host: 127.0.0.1
    # redis服务器的登录密码。
    password:
    # Redis服务器端口。
    port: 6379
  #
  # Session 配置
  session:
    # Session 类型
    # 相当于手动添加 @EnableRedisHttpSession 注释
    store-type: redis
  #
  # Thymeleaf 配置
  thymeleaf:
    # 是否启用模板缓存。
    cache: false
#
# 日志 配置
logging:
  level:
    web: debug
    cn.com.xuxiaowei: debug